version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/root/bitnami-docker-testlink/mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/testlink:latest'
    ports:
      - '8080:80'
    volumes:
      - '/root/bitnami-docker-testlink/apache_data:/bitnami/apache'
      - '/root/bitnami-docker-testlink/testlink_data:/bitnami/testlink'
      - '/root/bitnami-docker-testlink/php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      TESTLINK_USERNAME: admin
      TESTLINK_PASSWORD: admin
      TESTLINK_EMAIL: admin@woqi.me
      TESTLINK_LANGUAGE: zh_CN
